FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

WORKDIR /app

# Копируем зависимости
COPY project/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код, модели и CSV с названиями
COPY project/src/ ./src/
COPY project/artifacts/models/ ./artifacts/models/
COPY project/data/raw/ogyeiv2/extracted_sentences.csv ./data/raw/ogyeiv2/

# Создаём папку для логов
RUN mkdir -p /app/logs

EXPOSE 8000

CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]